export const LIST_CONTACTS_STARTED = 'LIST_CONTACTS_STARTED';
export const LIST_CONTACTS_SUCCEEDED = 'LIST_CONTACTS_SUCCEEDED';
export const LIST_CONTACTS_FAILED = 'LIST_CONTACTS_FAILED';
export const listContacts = () => ({ type: LIST_CONTACTS_STARTED });
